config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/about'

  get 'static_pages/contact'

  get '/index' => 'static_pages#index'

  get '/howitworks' => 'static_pages#howitworks'

  get '/team' => 'static_pages#team'

  get '/seekerssurvey' => 'surveys#seekers'

  get '/ownerssurvey' => 'surveys#owners'

  get '/browseseekers' => 'browse#seekers'

  get '/browseowners' => 'browse#owners'

  get '/deviseshow' => 'devise#show'

  devise_for :users
  resources :users, :surveys, :browses

  root 'static_pages#index'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def contact
  end

  def howitworks
  end

  def index
  end

  def team
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/howitworks.html.erb
	<!DOCTYPE html>
		<html>
		<head>
		  <title>Padibilityweb</title>
		  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		  <%= csrf_meta_tags %>
		</head>
		
		<body>
			<div id="wrap">
  				<div id="main" class="container clear-top">
					<div id="manual"><h2>How it works</h2>
						<p>Padibility recognizes that finding a place to stay should not and cannot occur independently of finding a person to room with. Padibility uses a data-driven compatibility matching algorithm to match those with "pads" and are looking for roommates with those seeking them, and vice-versa:</p>
						<ol>
							<li>Fill out a brief questionnaire about yourself and your ideal or current pad.</li>
							<li>Receive recommendations and browse the profiles of pad seekers or pad owners who best fit your 
							needs.</li> 
							<li>Once you are interested in discussing the possibility of living with someone, send them a Request. They will be notified of your invite and upon acceptance, you can chat further.</li>
							<li>Confirm your roommate selection or Pass and keep on browsing!"</li>
							</ol></div>
						</div>
					</div>
		</body>
	</html>

app/views/static_pages/index.html.erb
	<!DOCTYPE html>
		<html>
		<head>
		  <title>Padibilityweb</title>
		  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		  <%= csrf_meta_tags %>
		</head>
		
		<body>
	<div class="intro">
		<%= image_tag("padibility_kangaroo.png") %>
		<p>Finding Room For People</p>
			
		<ul class="entrance">
			<li class="pad"><%= link_to 'Need a Pad?', seekerssurvey_path %></li>
			<li class="pad"><%= link_to 'Got a Pad?', ownerssurvey_path %></li>
			<li class="pad"><%= link_to 'Browse Pad Seekers', browseseekers_path %></li>
			<li class="pad"><%= link_to 'Browse Pad Owners', browseowners_path %></li>
			<li class="learn">Learn More</li></a>
		</ul>
		</div>
		<%= yield %>
		</body>
		</html>

app/views/static_pages/team.html.erb
	<!DOCTYPE html>
		<html>
		<head>
		  <title>Padibilityweb</title>
		  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		  <%= csrf_meta_tags %>
		</head>
		
		<body>
<div id="lineup">
	<h2>The Team</h2>
	<p>Padibility originated among a group of friends at Harvard University who met in the same dorm entryway during their freshman year. Their stressful summer housing searches prompted a simple question: what if the same data-driven process that matched us at Harvard could be made available to countless others?</p>	
	<table>
		<tbody>
		<tr>
			<td><img class="headshot" src="http://padibility.com/img/najineg.jpg" height="250" width="170" />
					<h2>Naji Filali</h2>
					<p>Naji is the Executive Team Manager and Header of Operations and Outreach to real estate firms. He's tasked with building a network of trusted brokerage.</p></td>
				<td class="staff"><img class="headshot" src="http://padibility.com/img/timneg.jpg" height="250" width="170" />
					<h2>Tim Hopper</h2>
					<p>Tim is the Chief Strategist and Marketing Manager. He manages outreach efforts to potential consumers through existing campus-based social networks.</p>
				</td>
				<td id="linear" class="staff"><img class="headshot" src="http://padibility.com/img/angieneg.jpg" height="250" width="170" />
					<h2>Angie Peng</h2>
					<p>Angie is the Market Research Manager. She has experience in management consulting and finance and specializes in consumer behavior analysis.</p>
				</td>
		</tr>
		<tr class="dos">
			<td id="linear" class="staff"><img class="headshot" src="http://i.imgur.com/xFSTrDN.jpg?1" height="250" width="170" />
					<h2>Charles Walker</h2>
					<p>Charles is the Junior Web Developer. He is tasked with designing and maintaining the web site.</p>
			</td>
			<td class="staff"><img class="headshot" src="http://padibility.com/img/brandonneg.jpg" height="250" width="170" />
				<h2>Brandon Gerberich</h2>
				<p>Brandon is the Chief Data Science Officer. He is tasked with optimizing matching and user experience using emergent social trends</p>
			</td>
</tr>
</tbody>
</table>
</div>
</body>
</html>