config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/about'

  get 'static_pages/contact'

  get '/index' => 'static_pages#index'

  get '/howitworks' => 'static_pages#howitworks'

  get '/team' => 'static_pages#team'

  get '/seekerssurvey' => 'surveys#seekers'

  get '/ownerssurvey' => 'surveys#owners'

  get '/browseseekers' => 'browse#seekers'

  get '/browseowners' => 'browse#owners'

  get '/deviseshow' => 'devise#show'

  devise_for :users
  resources :users, :surveys, :browses

  root 'static_pages#index'

end

app/views/layouts/_menu.html.erb
<div class="collapse navbar-collapse" id="navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Posts', posts_path %></li>
            <% if current_user %>
            <li><%= link_to 'Edit Profile',edit_user_registration_path %></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>

            <li class="round-image-50"><%= image_tag(current_user.avatar.url(:thumb)) %></li>

            <% else %>
            <li><%= link_to 'Login', new_user_session_path %></li>
            <% end %>
        </ul>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
	<html>
	<head>
	  <title>Padibilityweb</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap.min.css">
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
		<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
	  <%= csrf_meta_tags %>
	</head>
	<header class="" >
		<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
      </button>
    </div>

			<div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li><%= link_to "#{image_tag("home.png")}".html_safe, root_path %></li>
				</ul>

				<ul class="nav navbar-nav navbar-right">
					<li><%= link_to 'How it Works', howitworks_path %></li>
					<li><%= link_to 'The Team', team_path %></li>
					<li><%= link_to 'Contact Us', team_path %></li>
					<li>
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							<span class="caret"></span> 
							<span id="gutter"><%= current_user.email%> <%= image_tag current_user.avatar.url(:thumb) %></span>
						</a>
						<ul class="dropdown-menu" role="menu">
						<% if user_signed_in? %>
							<li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
							<li><%= link_to 'Log Out',destroy_user_session_path, :method => :delete %></li>
							<li><%= link_to "I'm All Set", "#" %></li>
						<% else %>
							<li><%= link_to 'Sign In', new_user_session_path %></li>
							<li><%= link_to 'Sign Up', new_user_registration_path %></li>
						<% end %>
						</ul>
					</li>
				</ul>
			</div>
		</nav>







	<!-- 		<span class="menu-trigger">MENU</span>
			<div class="nav"><span class-"navbar-header">
			<span class="navbar-brand"><%= link_to "#{image_tag("home.png")}".html_safe, root_path %></span></span>
			<ul class="clearfix pull-right"><li class="glow"><%= link_to ("<span>How it Works</span>").html_safe, howitworks_path %></li>
				<li class="glow"><%= link_to ("<span>The Team</span>").html_safe, team_path %></li>
				<li class="glow"><%= link_to ("<span>Contact Us</span>").html_safe %></li>
					<% if user_signed_in? %>
					<li id="settings" class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="caret"></span> <span id="gutter"><%= current_user.email%> <%= image_tag current_user.avatar.url(:thumb) %></span>
	    <ul class="dropdown-menu" role="menu">
	    	<li id="update"><%= link_to 'Edit Profile', edit_user_registration_path %></li><br /><hr />
	      <li role="logout"><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li><br /><hr id="tablet" />
	      <li role="allset"><%= link_to ("<span>I'm All Set!</span>").html_safe, "#" %></li>
	    </ul>
	  </li></div>
					<% else %>
						<li id="settings">
						<li class="glow"><%= link_to 'Sign In', new_user_session_path %></li>
					<li class="glow">
						<%= link_to ("<span>Sign Up</span>").html_safe, new_user_registration_path %>
					</li>
					
			</ul>

		</div>
		<% end %> -->
	</header>
	<body>

	<%= yield %>

	<footer class="footer"><div id="copyright">Copyright Padibility 2014 <span class="pad_contact">Contact us: <a href="info@padibility.com">info@padibility.com</a></span></div>
		</footer>
	</body>
	</html>

app/views/layouts/browse.html.erb
<h2>Browse Seekers</h2>
	<h4>SORT BY:</h4><select class="sort">
		<option value="Compatibility">Compatibility</option>
		<option value="Update Recency">Update Recency</option>
		<option value="Price Range">Price Range</option>
		<option value="Distance from Me">Distance from Me</option>
		<option value="Register Date">Register Date</option>
	</select>
	<table id="seekers">
<% @surveys.each do |survey| %>
  <tr>
     <td><div class="cell"><%= image_tag user.avatar.url(:square) %>
       <p class="fullname"><%= survey.first_name %> <%= survey.last_name %></p>
       <p class="percent">78%</p></div>
   </td>
 </tr>

			<td><div class="cell"><%= image_tag user.avatar.url(:square) %>
				<p class="fullname"><%= @survey.first_name %> <%= @survey.last_name %></p><
				<p class="percent">51%</p></div>
				</td>
				<td><div class="cell"><%= image_tag user.avatar.url(:square) %>
				<p class="fullname"><%= @survey.first_name %> <%= @survey.last_name %></p>
				<p class="percent">75%</p></div></td>
		</tr>
		<tr>
			<td><div class="cell"><%= image_tag user.avatar.url(:square) %>
				<p class="percent">67%</p></div>
			</td>
			<td><div class="cell"><%= image_tag user.avatar.url(:square) %>
				<p class="fullname"><%= @survey.first_name %> <%= @survey.last_name %></p></p>
				<p class="percent">44%</p></div>
			</td>
			<td><div class="cell"><%= image_tag user.avatar.url(:square) %>
				<p class="fullname"><%= @survey.first_name %> <%= @survey.last_name %></p>
				<p class="percent">56%</p></div></td>
		</tr>
		<tr>
			<td><div class="cell">
				<p class="fullname"><%= @survey.first_name %> <%= @survey.last_name %></p>
				<p class="percent">59%</p></div></td>
			<td><div class="cell">
				<p class="fullname"><%= @survey.first_name %> <%= @survey.last_name %></p>
						<p class="percent">76%</p></div></td>
						<td><div class="cell">
				<p class="fullname"><%= @survey.first_name %> <%= @survey.last_name %></p>
							<p class="percent">60%</p></div>
		</tr>
		<tr>
			<td><div class="cell">
				<p class="fullname"><%= @survey.first_name %> <%= @survey.last_name %></p>
				<p class="percent">82%</p></div></td>
				<td><div class="cell">
				<p class="fullname"><%= @survey.first_name %> <%= @survey.last_name %></p>
					<p class="percent">35%</p></div></td>
						<td><div class="cell">
				<p class="fullname"><%= @survey.first_name %> <%= @survey.last_name %></p>
							<p class="percent">82%</p></div></td>
		</tr>
		<tr>
			<td><div class="cell">
				<p class="fullname"><%= @survey.first_name %> <%= @survey.last_name %></p>
					<p class="percent">84%</p></div>
				</td>
				<td><div class="cell">
				<p class="fullname"><%= @survey.first_name %> <%= @survey.last_name %></p>
					<p class="percent">54%</p></div></td>
					<td><div class="cell">
				<p class="fullname"><%= @survey.first_name %> <%= @survey.last_name %></p>
						<p class="percent">71%</p></div></td>
		</tr>
<% end %>
	</table>

app/views/layouts/owners.html.erb
<div id="wrapper">
                <div id="form_one_page" class="font one page link">
        <form action="/form_db_1" method="post" name="quiz" id="quiz">
                <h3 class="title">Providers' Questionnaire</h3>                
                <div class="holder">
                    <div>
                        <label for="housing">Type of housing</label>
                        <input type="radio" name="housing" value="Apartment">Apartment
                        <input type="radio" name="housing" value="House">House
                        <input type="radio" name="housing" value="Other">Other (Please specify): <input type="text" name="housing">
                        <label for="realty">What company do you represent?</label>
                        <input type="text" name="realty" />
                        <div class="button-holder">
                            <label for="availability">Availability</label>
                            <span class="availability"><input type="radio" name="availability" class="regular-radio" value="Room only"/>Only a room
                            <input type="radio" id="survey_type_3" name="survey_type" class="regular-radio" value="Both" checked/><label for="survey_type_3"></label><div class="radio-text">Both</div><br /></span>
                        </div>
                    </div>
                </div> 
                
            
                <div class="holder">
                    Your city <span class="expand">(We will be expanding to more cities in the coming weeks!)</span>
                </div>
                    <div class="button-holder">
                        <input type="radio" name="nycity" class="regular-radio" value="New York City" checked="checked"/><label for="nycity">New York City</label>
                        <input type="radio" id="moving_to_2" name="boston" class="regular-radio" value="Boston"/><label for="Boston">Boston</label>
                        <input type="radio" id="moving_to_3" name="washdc" class="regular-radio" value="Washington D.C."/><label for="washdc">Washington, D.C.</label>
                        <div class="roommates_both">
                        <input type="radio" id="sanf" name="moving_to" class="regular-radio" value="San Francisco"/><label for="sanf">San Francisco</label><br />
                        <input type="radio" id="moving_to_5" name="chitown" class="regular-radio" value="Chicago"/><label for="chitown">Chicago</label>
                        <input type="radio" id="moving_to_6" name="losa" class="regular-radio" value="Los Angeles"/><label for="losa">Los Angeles</label>
                        <input type="radio" id="moving_to_7" name="othercity" class="regular-radio" value="Other"/><label for="othercity">Other</label>
                        <input id="long" type="text" name="moving_to_other" placeholder="City Name" hidden/>
                        </div>
                    </div>
                </div>
            </div> <!-- End of holder -->     
            
             <div class="holder">
                <label>What is your gender?</label>
                <div class="button-holder">
                    <input type="radio" id="sex_1" name="malesex" class="regular-radio" value="Male" checked="checked" /><label for="malesex">Male</label><br />
                    <input type="radio" id="sex_2" name="femalesex" class="regular-radio" value="Female"/><label for="femalesex">Female</label><br />
                    <input type="radio" id="sex_3" name="othersex" class="regular-radio" value="Other"/><label for="othersex">Other</label><br />
                </div>
            </div> 

            <div class="holder">
                <label>Are you okay with co-ed housing?</label>
                <div class="button-holder">
                    <input type="radio" id="coed_1" name="coedyes" class="regular-radio" value="Yes"/><label for="coedyes">Yes</label><br />
                    <input type="radio" id="coed_2" name="coedno" class="regular-radio" value="No" checked="checked" /><label for="coedno">No</label><br />
                    
                </div>
            </div> 

            <div class="holder">
                <div>
                    <label for="age">How old are you?</label>
                    <input class="short" type="text" name="age" placeholder="Age" required="required"/>
                </div>
            </div>

                
            <div class"holder">
                <div class="housing_both">
                    <p>
                      <label for="amount">Monthly Price of Rent (per Person):</label>
                      <input type="text" name="rentprice" id="amount" style="border:0; color:#f6931f; font-weight:bold;">
                    </p>
                     
                    <div id="slider"></div>
                </div>
            </div> <!-- End of holder -->
            
            <div class="holder">
                <p>Move in date: <input type="text" name="move_in" id="datepicker-in" required="required"></p>
                <p>Move out date (optional): <input type="text" name="move_out" id="datepicker-out"></p>
            </div> <!-- End of holder -->

            <div class="holder">
                <div class="housing_both">
                    <p>How many bedrooms are in your pad?</p>
                    <div class="button-holder">
                        <input type="radio" id="bed_num_1" name="bedstudio" class="regular-radio" value="Studio" checked="checked"/><label for="bedstudio">Studio</label><br />
                        <input type="radio" id="bed_num_2" name="bedroomone" class="regular-radio" value="1"/><label for="bedroomone">1 Bedroom</label><br />
                        <input type="radio" id="bed_num_3" name="bedroomtwo" class="regular-radio" value="2"/><label for="bedroom2">2 Bedrooms</label><br />
                        <input type="radio" id="bed_num_4" name="bedroomthree" class="regular-radio" value="3"/><label for="bedroomthree">3</label><br />
                        <input type="radio" id="bed_num_5" name="bedroomfour" class="regular-radio" value="4+"/><label for="bedroomfour">4+ Bedrooms</label><br />
                    </div>
                    <p>How many bathrooms are in your pad?</p>
                    <div class="button-holder">
                        <input type="radio" id="bed_num_2" name="bedroomone" class="regular-radio" value="1"/><label for="bedroomone">1 Bathroom</label><br />
                        <input type="radio" id="bed_num_15" name="bedroomonefive" class="regular-radio" value="1"/><label for="bedroomonefive">1.5 Bathrooms</label><br />
                        <input type="radio" id="bed_num_3" name="bedroomtwo" class="regular-radio" value="2"/><label for="bedroom2">2 Bathrooms</label><br />
                        <input type="radio" id="bed_num_3" name="bedroom25" class="regular-radio" value="2"/><label for="bedroom25">2.5 Bathrooms</label><br />
                        <input type="radio" id="bed_num_4" name="bedroomthree" class="regular-radio" value="3"/><label for="bedroomthree">3 Bathrooms</label><br />
                        <input type="radio" id="bed_num_4" name="bedroomthreefive" class="regular-radio" value="3"/><label for="bedroomthreefive">3.5 Bathrooms</label><br />
                        <input type="radio" id="bed_num_5" name="bedroomfour" class="regular-radio" value="4+"/><label for="bedroomfour">4+ Bathrooms</label><br />
                    </div>
                </div>
            </div>
            <div class="holder">
                <label="roomlist">List all other rooms in your pad.</label>
                <input type="text" name="roomlist" value="list" />
            </div>
            <div class="holder">
                <span class="agerange">What is the age range of the residents in your building?</span>
                <label for="age_min">Age Min.</label>
                <input type="text" name="age_min" value="min" />
                <label for="age_max">Age Max.</label>
                <input type="text" name="age_max" value="max" />
                <label for="age_mode">What is the age mode (the most common age) of the residents in your building</label>
                <input type="text" name="age_mode" value="max" />
            </div>

            <div class="holder">
                <div class="housing_both">
                    <p>What amenities are in your pad?</p>
                    <div class="button-holder">
                        <input type="checkbox" id="amenities_1" name="balcony" class="regular-checkbox" value="Balcony" /><label for="balcony">Balcony</label><br />
                        <input type="checkbox" id="amenities_2" name="dishwasher" class="regular-checkbox" value="Dishwasher"/><label for="dishwasher">Dishwasher</label><br />
                        <input type="checkbox" id="amenities_3" name="doorman" class="regular-checkbox" value="Doorman"/><label for="doorman">Doorman</label><br />
                        <input type="checkbox" id="amenities_4" name="elevator" class="regular-checkbox" value="Elevator"/><label for="elevator">Elevator</label><br />
                        <input type="checkbox" id="amenities_5" name="furnished" class="regular-checkbox" value="Furnished"/><label for="furnished">Furnished</label><br />
                        <input type="checkbox" id="amenities_6" name="garage" class="regular-checkbox" value="Garage"/><label for="garage">Garage</label><br />
                        <input type="checkbox" id="amenities_7" name="gym" class="regular-checkbox" value="Gym"/><label for="gym">Gym</label><br />
                        <input type="checkbox" id="amenities_8" name="unitlaundry" class="regular-checkbox" value="In-Unit Laundry"/><label for="unitlaundry">In-Unit Laundry</label><br />
                        <input type="checkbox" id="amenities_9" name="laundryroom" class="regular-checkbox" value="Laundry Room"/><label for="laundryroom">Laundry Room</label><br />
                        <input type="checkbox" id="amenities_10" name="outdoor" class="regular-checkbox" value="Outdoor Space"/><label for="outdoor">Outdoor Space</label><br />
                        <input type="checkbox" id="amenities_11" name="parking" class="regular-checkbox" value="Parking Space"/><label for="parking">Parking</label><br />
                        <input type="checkbox" id="amenities_12" name="terrace" class="regular-checkbox" value="Terrace"/><label for="terrace">Terrace</label><br />
                    </div>
                </div>
            </div>

            <div class="holder">
                 <div>
                    <p>Are pets allowed in your pad?</p>
                    <div class="button-holder">
                        <input type="radio" id="pets_1" name="petsyes" class="regular-radio" value="Yes" checked="checked"/><label for="petsyes">Yes</label><br />
                        <input type="radio" id="pets_2" name="petsno" class="regular-radio" value="No"/><label for="petsno">No</label><br />
                        <input type="radio" id="pets_3" name="petsdc" class="regular-radio" value="Do not care"/><label for="petsdc">Don&#39;t care</label><br />
                    </div>
                </div>
            </div> 

            <div>
                <p>What is the address of your pad?</p>
                <input id="long" type="text" name="address" placeholder="Address" required="required"/>
            </div>

            <div class="housing_only">
                <input type="checkbox" id="terms_1" name="terms" class="regular-checkbox terms_class" value="read"/><label for="terms">I have read the <a href="/terms" target="_blank">Terms & Conditions</a></label><br />
                <span class="terms_error">Please read the Terms & Conditions</span>
            </div>
            
            <div class="circle_wrapper roommates_both">
                <div class="dark_circle" ></div>
                <div class="light_circle" ></div>
                <div class="light_circle" ></div>
            </div>
            <div class="roommates_both">
                <input id="next1" class="nextbutton one pages" type="submit" name="submit" value="Save and continue >"/>
            </div>
            <div class="housing_only">
                <div class="submit_button">
                <input id="submit_room_only" class="nextbutton one pages submitbutton" type="submit" name="submit" value="Submit!" disabled/>
                </div>
            </div>

        </form>
        <form action="FileUpload.php" method="post" enctype="multipart/form-data">
    <label for="upload">File:</label>
    <input type="file" name="upload" id="upload"><br/>
    <input type="submit" name="submit" value="Upload">
</form>
        </div> <!-- End of page one -->
        
        
        
         
    </div> <!-- End of wrapper -->

app/views/layouts/profile.html.erb
<div id="profile">
		<div class="general">
		<img src="images/charlie_thumb.jpg" height="200" width="200" />
		<span class="basics"><h2><%= @survey.name %></h2>
		<p><%= @survey.user_status %><br />
			Seeking <strong><%= @survey.roommates_estimate %><%= @survey.coed %></strong> roommates ages <strong><%=  @survey.age_min %> - <%=  @survey.age_min %></strong><br />
			Currently lives in <strong><%= @survey.hometown %></strong><br />
			Seeking to live in <strong><%= @survey.housing_type %></strong> in <strong><%= @survey.moving_to %></strong><br />
			Seeking to spend up to <strong><%= @survey.max_rent %></strong></p></span>
		</div>
		<p>Goes to sleep at <strong><%= @survey.bedtime %></strong><br />
			Wakes up at <strong><%=  @survey.wake_up %></strong><br />
			Sociability: <strong><%=  @survey.sociability %></strong><br />
			Tidiness: <strong><%=  @survey.tidiness %></strong><br />
			Question for Potential Roommate: <strong><%=  @survey.question %></strong> <span class="answer">Answer</span><br />
			Ideal Noise Level: <strong><%=  @survey.noise %></strong><br />
			Political Views: <strong><%= @survey.political %></strong><br />
			Religious Views: <strong><%=  @survey.religion %></strong><br />
			Activities & Interests: <strong><%=  @survey.interest %></strong><br />
			<span class="nosmoke">Doesn't smoke</span><span class="smoking">Smokes <%=  @survey.smokeoften %><%=  @survey.smokesocially %></span><br />
			<span class="nodrink">Doesn't drink</span><span class="drinking">Drinks <%=  @survey.drinkoften %><%=  @survey.drinksocially %></span><br />
			<span class="nodrugs">Doesn't do drugs</span><span class="druggie">Does drugs <%=  @survey.drugsoften %><%=  @survey.drugssocially %></span><br />
			<span class="sexlife"><%=  @survey.sexualactivity %>
			</span>
			<strong><%=  @survey.sexprivacy %></strong> with <strong>sex</strong><br />
			<strong><%=  @survey.overnight %><%=  @survey.overnightoften %></strong><br />
			<strong><%=  @survey.roommate_pet %><%=  @survey.apartment_pet %></strong></p>
			<hr />
			<p class="edit">Edit Profile</p>
	</div>